### ISSUE TITLE
Cannot run integration after update

### ISSUE THREAD

**Issue by krzysiek2788** [mrk-its/homeassistant-blitzortung#43]
Hi after last update Blitzortung cannot start:
![image](https://user-images.githubusercontent.com/61471407/146537163-3a822f38-2d90-4c3d-a6de-46c641885e6b.png)
Error from logs:

Logger: homeassistant.setup
Source: setup.py:316
First occurred: 08:27:21 (2 occurrences)
Last logged: 12:19:34

Unable to prepare setup for platform blitzortung.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/usr/src/homeassistant/homeassistant/helpers/device_registry.py)).

**Comment by yfands** [comment]
Me neither...

After the Hacs, delete, reinstall issues I have to concur that I got the same error as  krzysiek2788

Regards Frank

**Comment by DaleGervais** [comment]
I too have the same problem as krzysiek2788 after allowing this upgrade.

**Comment by vibor-sum** [comment]
I have same problem after last update.

**Comment by Spirituss** [comment]
The same is here. After update it stops working. Moreover, it can't be now downgraded via HACS.

**Comment by rocketdyke** [comment]
same problem. downgrade impossible

**Comment by DaleGervais** [comment]
Upgraded to the following versions:

Version	core-2021.9.7
Installation Type	Home Assistant Core
Development	false
Supervisor	false
Docker	false
User	root
Virtual Environment	true
Python Version	3.8.10
Operating System Family	Linux
Operating System Version	5.14.18-100.fc33.x86_64
CPU Architecture	x86_64
Timezone	America/New_York
Home Assistant Community Store


MANAGE
GitHub API	ok
Github API Calls Remaining	4958
Installed Version	1.18.0
Stage	running
Available Repositories	996
Installed Repositories	6

Still getting the following error:

Logger: homeassistant.setup
Source: setup.py:317 
First occurred: 8:54:40 PM (1 occurrences) 
Last logged: 8:54:40 PM

Unable to prepare setup for platform blitzortung.sensor: Platform not found (cannot import name 'DeviceEntryType' from 'homeassistant.helpers.device_registry' (/snap/home-assistant-snap/398/lib/python3.8/site-packages/homeassistant/helpers/device_registry.py)).

**Comment by tanker11** [comment]
Same issue here. Is there a known reason for this?

**Comment by Spirituss** [comment]
It works in 2021.12. So it seems to be due to HA architecture changes.

**Comment by krzysiek2788** [comment]
Yes with 2021.12.09 version all is working fine. Closing.

**Comment by rocketdyke** [comment]
closed? what about people running 2021.11.5 and the chance for downgrading?
